# used by https://takahirom.github.io/gradle-version-catalog-converter/
[versions]
com-android-tools-build = "7.4.2"
org-jetbrains-kotlin = "1.8.10"
gradle-plugin-com-cookpad-android-plugin = "1.2.8"
androidx-core = "1.10.1"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-swiperefreshlayout = "1.1.0"
androidx-preference = "1.2.1"
androidx-security = "1.1.0-alpha05"
androidx-lifecycle = "2.6.1"
androidx-navigation = "2.5.3"
junit = "4.13.2"
com-google-truth = "1.1.5"
androidx-test-ext = "1.1.5"
androidx-test-espresso = "3.5.1"
androidx-room = "2.5.0"
com-google-android-material = "1.9.0"
io-insert-koin = "3.4.3"
com-google-code-gson = "2.10.1"
com-squareup-leakcanary = "2.12"

[libraries]
# classpath
com-android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "com-android-tools-build" }
org-jetbrains-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
gradle-plugin-com-cookpad-android-plugin = { module = "gradle.plugin.com.cookpad.android.plugin:plugin", version.ref = "gradle-plugin-com-cookpad-android-plugin" }

# androidx
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "androidx-security" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
# nav
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
# room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }

# test
junit = { module = "junit:junit", version.ref = "junit" }
com-google-truth = { module = "com.google.truth:truth", version.ref = "com-google-truth" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }

# その他
org-jetbrains-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "org-jetbrains-kotlin" }
com-google-android-material = { module = "com.google.android.material:material", version.ref = "com-google-android-material" }
io-insert-koin-android = { module = "io.insert-koin:koin-android", version.ref = "io-insert-koin" }
com-google-code-gson = { module = "com.google.code.gson:gson", version.ref = "com-google-code-gson" }
com-squareup-leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "com-squareup-leakcanary" }

[plugins]