name: Android CI

on: 
  workflow_dispatch:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: |
        cd ./AndroidApp
        chmod +x ./gradlew
    - name: Build with Gradle
      run: |
        cd ./AndroidApp
        ./gradlew build
